### PR TITLE
fix: prevent crash when v8 incorrectly merges static_initializer's

### LINKED ISSUE #5329: Use `useDefineForClassFields` with `coverage-v8` and vitest workspace cause error
### Describe the bug

I'm using vitest and a coverage error showed up after I added a `static` class field:

```
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
 ❯ RangeTree.fromSortedRanges node_modules/.pnpm/@bcoe+v8-coverage@0.2.3/node_modules/@bcoe/v8-coverage/dist/lib/range-tree.js:27:39
 ❯ normalizeFunctionCov node_modules/.pnpm/@bcoe+v8-coverage@0.2.3/node_modules/@bcoe/v8-coverage/dist/lib/normalize.js:74:41
 ❯ Object.deepNormalizeScriptCov node_modules/.pnpm/@bcoe+v8-coverage@0.2.3/node_modules/@bcoe/v8-coverage/dist/lib/normalize.js:59:9
 ❯ mergeScriptCovs node_modules/.pnpm/@bcoe+v8-coverage@0.2.3/node_modules/@bcoe/v8-coverage/dist/lib/merge.js:59:21
 ❯ mergeProcessCovs node_modules/.pnpm/@bcoe+v8-coverage@0.2.3/node_modules/@bcoe/v8-coverage/dist/lib/merge.js:34:21
 ❯ node_modules/.pnpm/@vitest+coverage-v8@1.3.1_vitest@1.3.1/node_modules/@vitest/coverage-v8/dist/provider.js:265:22
 ❯ V8CoverageProvider.reportCoverage node_modules/.pnpm/@vitest+coverage-v8@1.3.1_vitest@1.3.1/node_modules/@vitest/coverage-v8/dist/provider.js:262:11
 ❯ Vitest.reportCoverage node_modules/.pnpm/vitest@1.3.1_@types+node@20.11.24/node_modules/vitest/dist/vendor/cac.wWT9ELdg.js:11918:7
 ❯ async node_modules/.pnpm/vitest@1.3.1_@types+node@20.11.24/node_modules/vitest/dist/vendor/cac.wWT9ELdg.js:11709:7
```

I tried to minimize the reproduction demo and it seems like it is related to `useDefineForClassFields`. See the Reproduction section for details.

### Reproduction

A minimal reproduction repo is created at: https://github.com/colinaaa/vitest-v8-repro

Just run

- `pnpm install`
- `pnpm vitest --coverage`

to reproduce the issue.

Note that any of these will eliminate the error:

- removing `useDefineForClassFields` in `tsconfig.json`
- replacing `coverage-v8` with `coverage-istanbul`
- removing `static Bar`
- replacing `static Baz` with `require.resole('./loader.js')`
- not using vitest workspace

### System Info

```shell
System:
    OS: macOS 14.0
    CPU: (12) arm64 Apple M2 Max
    Memory: 14.89 GB / 96.00 GB
    Shell: 3.7.0 - /opt/homebrew/bin/fish
  Binaries:
    Node: 20.11.1 - ~/Library/Caches/fnm_multishells/77527_1709530742451/bin/node
    Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/77527_1709530742451/bin/yarn
    npm: 10.2.4 - ~/Library/Caches/fnm_multishells/77527_1709530742451/bin/npm
    pnpm: 7.33.6 - ~/Library/Caches/fnm_multishells/77527_1709530742451/bin/pnpm
  Browsers:
    Chrome: 122.0.6261.94
    Firefox Nightly: 115.0
    Safari: 17.0
  npmPackages:
    @vitest/coverage-v8: ^1.3.1 => 1.3.1 
    vitest: ^1.3.1 => 1.3.1 
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by AriPerkkio**
Fixes https://github.com/vitest-dev/vitest/issues/5329.

Reproduction:

```sh
ari ~/Git/reproductions (v8-merge) $ cat package.json 
{
  "name": "reproductions",
  "version": "1.0.0",
  "type": "module",
  "private": true,
  "scripts": {},
  "license": "MIT",
  "devDependencies": {
    "@bcoe/v8-coverage": "^0.2.3",
    "@types/node": "^20.11.24"
  }
}
ari ~/Git/reproductions (v8-merge) $ node -v; npm -v
v20.11.1
10.2.4
```

```ts
import { mergeProcessCovs } from "@bcoe/v8-coverage";
import { writeFileSync } from "node:fs";
import inspector from "node:inspector";

writeFileSync(
  "./source-file.js",
  `
export class Foo {
  static First = true ? 1 : 0;
  static Seoncd = 1;
}
`.trim(),
  "utf8"
);

const session = new inspector.Session();

session.connect();
session.post("Profiler.enable");
session.post("Profiler.startPreciseCoverage", {
  callCount: true,
  detailed: true,
});

await import("./source-file.js");

const coverage = await collectCoverage("source-file.js");
console.log(JSON.stringify(coverage, null, 2));

mergeProcessCovs([coverage]);

async function collectCoverage(filename) {
  return new Promise((resolve, reject) => {
    session.post("Profiler.takePreciseCoverage", async (error, coverage) => {
      if (error) return reject(error);

      const result = coverage.result.filter((entry) =>
        entry.url.includes(filename)
      );

      resolve({ result });
    });
  });
}
```

```
ari ~/Git/reproductions (v8-merge) $ node index.mjs 
{
  "result": [
    {
      "scriptId": "139",
      "url": "file:///rootdirs/reproductions/source-file.js",
      "functions": [
        {
          "functionName": "",
          "ranges": [
            {
              "startOffset": 0,
              "endOffset": 72,
              "count": 1
            }
          ],
          "isBlockCoverage": true
        },
        {
          "functionName": "<static_initializer>",
          "ranges": [
            {
              "startOffset": 52,
              "endOffset": 69,
              "count": 1
            },
            {
              "startOffset": 45,
              "endOffset": 48,
              "count": 0
            }
          ],
          "isBlockCoverage": true
        }
      ]
    }
  ]
}
/rootdirs/reproductions/node_modules/@bcoe/v8-coverage/dist/lib/range-tree.js:27
                [parent, parentCount] = stack[stack.length - 1];
                                      ^

TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at RangeTree.fromSortedRanges (/rootdirs/reproductions/node_modules/@bcoe/v8-coverage/dist/lib/range-tree.js:27:39)
    at normalizeFunctionCov (/rootdirs/reproductions/node_modules/@bcoe/v8-coverage/dist/lib/normalize.js:74:41)
    at Object.deepNormalizeScriptCov (/rootdirs/reproductions/node_modules/@bcoe/v8-coverage/dist/lib/normalize.js:59:9)
    at mergeScriptCovs (/rootdirs/reproductions/node_modules/@bcoe/v8-coverage/dist/lib/merge.js:59:21)
    at mergeProcessCovs (/rootdirs/reproductions/node_modules/@bcoe/v8-coverage/dist/lib/merge.js:34:21)
    at file:///rootdirs/reproductions/index.mjs:30:1

Node.js v20.11.1
```

### CODE REVIEW

**Review by sagupta1001 — APPROVED** [review]

**Comment by sagupta1001** [comment]
@AriPerkkio @bcoe would it be possible to merge this PR?

**Comment by ebrpol** [comment]
I'd also greatly appreciate it if this MR could be merged

**Comment by AriPerkkio** [comment]
If you are running into this issue, try upgrading your Node to latest version. Looks like there has been some fixes related to V8 coverage reporting.

**Comment by ebrpol** [comment]
> If you are running into this issue, try upgrading your Node to latest version. Looks like there has been some fixes related to V8 coverage reporting.

Thanks for the heads up!

Would it be possible to merge this MR nonetheless? I am working on a large project on Node 18, in which it's very costly to upgrade to Node 20.

**Comment by ebrpol** [comment]
I've tested on Node 20.12.2 and it still has the same issue. Node 22.1.0 does not have this issue indeed!

I think a lot of people will still be on an LTS version, so I think it will be helpful if this MR can be merged.

**Comment by Wroud** [comment]
I would appreciate it if you would merge the PR

**Pull request merged**
